# File: .github/workflows/ci-cd-pipeline.yml
#test branch
name: CI/CD Pipeline for Flask Hello World App

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. Test Stage 2
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: echo "No Python tests defined, skipping..."

  # 2. Build Stage 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/hello-world-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest

      - name: Print success message
        run: |
          echo "✅ Build completed successfully!"
          echo "Image pushed to Docker Hub as: ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest"

  deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-azure-webapp'
        images: '${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest'
