

name: CI/CD Pipeline for Flask Hello World App

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. Test Stage (Updated for Python/Flask)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest
        # For now, we'll use a placeholder since you might not have tests.
        # Later, you can use pytest, unittest, etc.
        

  # 2. Build Stage (Docker) - This part stays mostly the same
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/hello-world-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest